# NumPy package

NumPy is a remarkable Python library for computing, arithmetics and linear algebra.
it can do it in an efficient way.

### Why we should use NumPy instead of Python lists?
- NumPy is much faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.
- NumPy support multidimensional array data structures that can represent vectors and matrices.
- NumPy is optimized for matrix operations, and it allows us to do Linear Algebra operations effectively and efficiently,
- NumPy has a large number of optimized built-in mathematical functions. 

Here is the snippet for how using NumPy library.

In [56]:
#import numpy in a convention way
import numpy as np
print(np.__version__)

1.26.4


# Creating NumPy n-dimension array

### Using regular Python lists to Create ndarray
Create a rank 1 ndarray that only contains integers

In [57]:
x = np.array([1, 2, 3, 4, 5])
print('x = ', x)

x =  [1 2 3 4 5]


Creating a rank 2 ndarray using nested integers Python lists

In [58]:
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('Y = \n', Y)
print()

# We print information about Y
print('Y is an object of type:', type(Y))
print('Y has dimensions:', Y.shape)
print(f"Number of dimensions of Y ={Y.ndim} == {len(Y.shape)}")
print('Y has a total of', Y.size, 'elements.')
print(f"Total memory used (Bytes): {Y.nbytes}")
print('The elements in Y are of type:', Y.dtype)
print(f"Memory per element (Bytes): {Y.itemsize}")

Y = 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Y is an object of type: <class 'numpy.ndarray'>
Y has dimensions: (4, 3)
Number of dimensions of Y =2 == 2
Y has a total of 12 elements.
Total memory used (Bytes): 48
The elements in Y are of type: int32
Memory per element (Bytes): 4


##### setting element data type
**Remember** Unlike Python lists, all the elements of a ndarray must be of the same type.    
to see Numpy data types click [here](https://numpy.org/doc/stable/user/basics.types.html)

In [59]:
x = np.array([1, 2, 3, 4, 5],dtype=np.float64)
print('x = ', x)
print('elements type:', x.dtype)

x =  [1. 2. 3. 4. 5.]
elements type: float64


In [60]:
x = np.array([1, 2, 3, 4, 5],dtype=np.int64)
print('x = ', x)
print('elements type:', x.dtype)

x =  [1 2 3 4 5]
elements type: int64


### Using Built-in Functions to Create ndarrays


##### Range of integer numbers


In [61]:
x = np.arange(20).reshape(4, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


`np.arange(start,stop,step)`    
Remember start point is **inclusive** and stop index is **exclusive**

In [62]:
x=np.arange(1,30,3).reshape((2,5))
print(x)

[[ 1  4  7 10 13]
 [16 19 22 25 28]]


`np.linspace(start,stop,no)`  
even though the `np.arange()` function allows for non-integer steps, such as 0.3, the output is usually inconsistent, due to the finite floating point precision. For this reason, in the cases where non-integer steps are required, it is usually better to use the function `np.linspace()`.

In [63]:
g=np.linspace(1,100,10_000).reshape((100,100))
#print(f"{g}")
print(f"\tdimension of matrix: {g.shape}")
print(f"\telement type is {g.dtype}")

	dimension of matrix: (100, 100)
	element type is float64


Note:
>`np.reshape()` can take -1 as one of its dimension sizes. That signifies that NumPy should just figure out how big that particular axis needs to be based on the size of the other axes.

In [64]:
X = np.linspace(1,20,24).reshape(12,-1)
print(X.shape)
X = np.linspace(1,20,24).reshape(2,-1,3)
print(X.shape)

(12, 2)
(2, 4, 3)


##### Zeros array

In [65]:
#creating n-dimension zeros array
a=np.zeros((3,4))
print(f"zeros {a.shape[0]}×{a.shape[1]}=\n{a}")

zeros 3×4=
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


 ##### Ones array.     
 Creating n-dimension 1 array

In [66]:
b=np.ones((4,3))
print(f"ones {b.shape[0]}×{b.shape[1]}=\n{b}")

ones 4×3=
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##### full array
Creating n-dimension full of custom number

In [67]:
c=np.full((4,3),7.)
print(c)
print(f"element type is {c.dtype}")

[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]
element type is float64


In [68]:
c1=np.full((4,3),7,dtype=np.int64)
print(c1)
print(f"element type is {c1.dtype}")

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
element type is int64


##### Identity Matrices

In [69]:
x=np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


##### Diagonal Matrices

In [70]:
x=np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


##### Get diagonal elements of matrices

In [71]:
x=np.arange(1,26).reshape(5,5)
print(x)
d=np.diag(x)
print(f"main diag fo matrix:{d}")
d1=np.diag(x,1)
print(f"top of the main diag fo matrix:{d1}")
d1below=np.diag(x,-1)
print(f"below of the main diag fo matrix:{d1below}")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
main diag fo matrix:[ 1  7 13 19 25]
top of the main diag fo matrix:[ 2  8 14 20]
below of the main diag fo matrix:[ 6 12 18 24]


## Creating random ndarrays
### random values from $[0.0, 1.0)$ interval
Create a ndarray of the given shape with random floats in the half-open interval $[0.0, 1.0)$.

In [72]:
x=np.random.random((2,5))

#change the number of digits of precision for floating point output (default 8).
np.set_printoptions(precision=4)

print('x=', x)


x= [[0.5132 0.8502 0.3672 0.228  0.7498]
 [0.7818 0.8534 0.2985 0.6452 0.9125]]


### Random integers
`np.random.randint(start, stop, size = shape)`    
 - Creates a ndarray of the given shape with random integers in the half-open interval [start, stop)
 - If stop is None (the default), then results are from [0, start).
 - Default size is None, in which case a single value is returned.

In [73]:
x=np.random.randint(0,11,(2,5))
print(x)

[[7 4 6 7 6]
 [5 0 6 6 1]]


In [74]:
x=np.random.randint(11)
print('x=', x)

x= 10


### Normal distribution
`np.random.normal(mu=0.0, sigma =1.0, size=None)`   
Draw samples from Normal distribution

`np.random.standard_normal(size)`
Draw samples from a standard Normal distribution (mean=0, stdev=1)

In [75]:
mu, sigma = 0, 1 # mean and standard deviation
s = np.random.normal(mu, sigma, (100,1000))
print(f"mu={np.mean(s)}")
print(f"std={np.std(s, ddof=1)}")

mu=-5.464840285469098e-05
std=1.000629939727181


# Save and load numpy ndarrays

In [76]:
#create a sample np.ndarray
x = np.array([1, 2, 3, 4, 5])

# save x into the current directory in a file named: "my_array.npy"
np.save('my_array', x)
#load the saved np.ndarray in file "my_array.npy"
y = np.load('my_array.npy')

# We print y
print('y = ', y)
print()

# print information about the ndarray we have just loaded
print('y is an object of type:', type(y))
print('The elements in y are of type:', y.dtype)


y =  [1 2 3 4 5]

y is an object of type: <class 'numpy.ndarray'>
The elements in y are of type: int32


# Permutation
`random.permutation(x)` 
- If `x` is an integer, randomly permute `np.arange(x)`. 
- If `x` is an array, make a copy and shuffle the elements randomly.
- If `x` is a multi-dimensional array, it is only shuffled along its **first index**.  


In [77]:
x=np.random.permutation(10)
print(x)

[2 6 7 0 8 5 9 1 4 3]


In [78]:
arr = np.arange(9).reshape((3, 3))
x=np.random.permutation(arr)
print(x)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


# Accessing  elements in ndarrays

## Indexing and slicing
### Accessing one dimensional ndarray

In [79]:
x = np.array([1, 2, 3, 4, 5])

print(f"x[0] = {x[0]}")
print(f"x[-1] = {x[-1]}")
print(f"x[1:3] = {x[1:3]}")
print(f"x[3:] = {x[3:]}")
print(f"x[-2:] = {x[-2:]}")
print(f"x[:] = {x[:]}")

x[0] = 1
x[-1] = 5
x[1:3] = [2 3]
x[3:] = [4 5]
x[-2:] = [4 5]
x[:] = [1 2 3 4 5]


### Accessing two-dimensional ndarray

In [80]:
x = np.arange(1,13).reshape(3,4)
print(f"x=\n{x}")
print()
print(f"x[0] = {x[0]}")
print(f"x[-1] = {x[-1]}")
print(f"x[1:3] =\n{x[1:3]}\n")
print(f"x[1:] = \n{x[1:]}\n")
print(f"x[-2:] = \n{x[-2:]}\n")
print(f"x[:-2] = {x[:-2]}\n")

x=
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0] = [1 2 3 4]
x[-1] = [ 9 10 11 12]
x[1:3] =
[[ 5  6  7  8]
 [ 9 10 11 12]]

x[1:] = 
[[ 5  6  7  8]
 [ 9 10 11 12]]

x[-2:] = 
[[ 5  6  7  8]
 [ 9 10 11 12]]

x[:-2] = [[1 2 3 4]]


In [81]:
x = np.arange(1,13).reshape(3,4)
print(f"x=\n{x}")
print()
print(f"x[0,0] = {x[0,0]}")
print(f"x[0,3] = {x[0,3]}")
print(f"x[1,:] = {x[1,:]}")
print(f"x[:,1] = {x[:,1]}")
print(f"x[1:2,1:2] = {x[1:2,1:2]}\n")#remeber exclusive ant end
print(f"x[1:3,1:3] = \n{x[1:3,1:3]}\n")
print(f"x[1:3,1:] = \n{x[1:3,1:]}")

x=
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,0] = 1
x[0,3] = 4
x[1,:] = [5 6 7 8]
x[:,1] = [ 2  6 10]
x[1:2,1:2] = [[6]]

x[1:3,1:3] = 
[[ 6  7]
 [10 11]]

x[1:3,1:] = 
[[ 6  7  8]
 [10 11 12]]


In [82]:
x = np.arange(1,13).reshape(3,4)
print(f"x=\n{x}")
print()
print(f"x[0,0] = {x[0,0]} \t\t type:{type(x[0,0])}")
print(f"x[0,3] = {x[0,3]}")
print(f"x[1,:] = {x[1,:]}")
print(f"x[:,1] = {x[:,1]}")
print(f"x[1:2,1:2] = {x[1:2,1:2]}  \t type:{type(x[1:2,1:2])}\n")#remeber exclusive ant end
print(f"x[1:3,1:3] = \n{x[1:3,1:3]} ]")
print(f"x[1:3,1:] = \n{x[1:3,1:]}")

x=
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,0] = 1 		 type:<class 'numpy.int32'>
x[0,3] = 4
x[1,:] = [5 6 7 8]
x[:,1] = [ 2  6 10]
x[1:2,1:2] = [[6]]  	 type:<class 'numpy.ndarray'>

x[1:3,1:3] = 
[[ 6  7]
 [10 11]] ]
x[1:3,1:] = 
[[ 6  7  8]
 [10 11 12]]


## Mask And Filter

A **mask** is an array that has the exact same shape as your data, but instead of your values, it holds Boolean values: either True or False. You can use this mask array to index into your data array in nonlinear and complex ways. It will return all the elements where the Boolean array has a True value.

In [83]:
X = np.arange(25).reshape(5, 5)

# We print X
print()
print('Original X = \n', X)
print()
##Creating a mask
mask= X > 10
print(f'mask is :\n {mask}')
print('The masked elements in X:', X[mask])
# We use Boolean indexing to select elements in X:
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# We use Boolean indexing to assign the elements that are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

# We print X
print()
print('X = \n', X)
print()



Original X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

mask is :
 [[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
The masked elements in X: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]

X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


# Manipulating elements

In [84]:
x = np.arange(1,13).reshape(3,4)
print(f"x=\n{x}")
x[0,0] = 10
print(f"\nx[0,0] = 10\n{x}")
x[0,3] *= 10
print(f"\nx[0,3] *= 10\n{x}")
#change a row
x[1,:]=[50, 60, 70, 80]
print(f"\nx[1,:]=[50 60 70 80]\n{x}")
#change column
x[:,-1]=[1,2,3]
print(f"\nx[:,-1]=[1,2,3]\n{x}")
x[1:3,1:]=[[11, 12,13],[14, 15,16]]
print(f"\nx[1:3,1:]=[[11, 12, 13],[14, 15, 16]]\n{x}")

x=
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,0] = 10
[[10  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3] *= 10
[[10  2  3 40]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[1,:]=[50 60 70 80]
[[10  2  3 40]
 [50 60 70 80]
 [ 9 10 11 12]]

x[:,-1]=[1,2,3]
[[10  2  3  1]
 [50 60 70  2]
 [ 9 10 11  3]]

x[1:3,1:]=[[11, 12, 13],[14, 15, 16]]
[[10  2  3  1]
 [50 11 12 13]
 [ 9 14 15 16]]


## Concatenation and split

- `np.stack`: Stack a sequence of arrays along a new axis.
- `np.hstack`: Stack arrays in sequence horizontally (column wise).
- `np.vstack`: Stack arrays in sequence vertically (row wise).
- `np.dstack`: Stack arrays in sequence depth wise (along third dimension)


- `np.split`:Split array into a list of multiple sub-arrays of equal size.
- `np.hsplit`: Split array into multiple sub-arrays horizontally (column wise).
- `np.vsplit`: Split array into multiple sub-arrays vertically (row wise).
- `np.dsplit`: Split array into multiple sub-arrays along the 3rd axis (depth).

- column_stack: Stack 1-D arrays as columns into a 2-D array.

In [85]:
x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])
horizontal_stack=np.hstack((x,y))
vertical_stack=np.vstack((x,y))
xy_concatenate=np.concatenate((x, y), axis=0)
print('x = \n', x)
print('y = \n', x)
print('np.hstack((x,y)) = \n', horizontal_stack)
print('np.vstack((x,y)) = \n', vertical_stack)
print('np.concatenate((x, y), axis=0) \n', xy_concatenate)


x = 
 [[1 2]
 [3 4]]
y = 
 [[1 2]
 [3 4]]
np.hstack((x,y)) = 
 [[1 2 5 6]
 [3 4 7 8]]
np.vstack((x,y)) = 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
np.concatenate((x, y), axis=0) 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Appending new elements
**Remember** When axis is specified, values must have the correct shape.

In [86]:
x = np.array([1, 2, 3, 4, 5])
print(f"x = {x}")
y1=np.append(x,6)
print(f"np.append(x,6)     ===>  y1 = {y1}")
y2=np.append(x,[7,8])
print(f"np.append(x,[7,8]) ===>  y2 = {y2}")

x = [1 2 3 4 5]
np.append(x,6)     ===>  y1 = [1 2 3 4 5 6]
np.append(x,[7,8]) ===>  y2 = [1 2 3 4 5 7 8]


In [87]:
# create a rank 2 ndarray 
Y = np.array([[1,2,3],[4,5,6]])
print('Original Y = \n', Y)

# append a new row 
y1 = np.append(Y, [[7,8,9]], axis=0)
print('\nv = \n', y1)
# append a new column 
y2 = np.append(Y,[[9],[10]], axis=1)
print('\nq = \n', y2)



Original Y = 
 [[1 2 3]
 [4 5 6]]

v = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

q = 
 [[ 1  2  3  9]
 [ 4  5  6 10]]


## Inserting new elements
`np.insert(ndarray, index, elements, axis)`   
Support a single scalar or a sequence with one element.

In [88]:
x = np.array([1, 2, 5, 6, 7])
print(f"x = {x}")

x = np.insert(x,2,[3,4])
print(f"np.insert(x,2,[3,4])     ===>  x = {x}")


x = [1 2 5 6 7]
np.insert(x,2,[3,4])     ===>  x = [1 2 3 4 5 6 7]


In [89]:
# We create a rank 2 ndarray 
Y = np.array([[1,2,3],[7,8,9]])
print('Original Y = \n', Y)

# We insert a row between the first and last row of y
w = np.insert(Y,1,[4,5,6],axis=0)
print('\nw = \n', w)

# We insert a column full of 5s between the first and second column of y
v = np.insert(Y,1,5, axis=1)
print('\nv = \n', v)

v0 = np.insert(Y,[1],[[10],[20]], axis=1)
print('\nv0 = \n', v0)
#v1=v0
v1 = np.insert(Y,1,[10,20], axis=1)
print('\nv1 = \n', v1)

v2 = np.insert(Y,[1,3],777, axis=1)
print('\nv2 = \n', v2)

v3 = np.insert(Y,[1,3],[11,13], axis=1)
print('\nv3 = \n', v3)

v4 = np.insert(Y,[1,3],[[10],[20]], axis=1)
print('\nv4 = \n', v4)

Original Y = 
 [[1 2 3]
 [7 8 9]]

w = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

v = 
 [[1 5 2 3]
 [7 5 8 9]]

v0 = 
 [[ 1 10  2  3]
 [ 7 20  8  9]]

v1 = 
 [[ 1 10  2  3]
 [ 7 20  8  9]]

v2 = 
 [[  1 777   2   3 777]
 [  7 777   8   9 777]]

v3 = 
 [[ 1 11  2  3 13]
 [ 7 11  8  9 13]]

v4 = 
 [[ 1 10  2  3 10]
 [ 7 20  8  9 20]]


## Delete elements
`numpy.delete(ndarray, obj, axis=None)`  
obj: slice, int or array of ints

In [90]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)
#delete row
Y=np.delete(x, 1, 0)
print(f"\nnp.delete(x, 1, 0) \ny =\n{Y}")
#delete column
Y=np.delete(x, 1, 1)
print(f"\nnp.delete(x, 1, 1) \ny =\n{Y}")

#delete the first and last column of x
Y = np.delete(x, [0,-1], axis=1)
print(f"\nnp.delete(x, [0,-1], 1) \ny =\n{Y}")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

np.delete(x, 1, 0) 
y =
[[ 1  2  3  4]
 [ 9 10 11 12]]

np.delete(x, 1, 1) 
y =
[[ 1  3  4]
 [ 5  7  8]
 [ 9 11 12]]

np.delete(x, [0,-1], 1) 
y =
[[ 2  3]
 [ 6  7]
 [10 11]]


# Cast data type

In [91]:
x = np.random.randint(1,11,size=(10,))
y=x.astype(np.float32)
print('x dtype is: ',x.dtype)
print('y dtype is: ',y.dtype)

x dtype is:  int32
y dtype is:  float32


# Sort ndarray

In [92]:
x = np.random.randint(1,11,size=(10,))

# We print x
print()
print('Original x = ', x)

# We sort x and print the sorted array using sort as a function.
print()
print('Sorted x (out of place):', np.sort(x))
print('x after sorting:', x)

# We sort x and print the sorted array using sort as a method.
x.sort()
# When we sort in place the original array is changed to the sorted array. To see this we print x again
print()
print('x after in place sorting:', x)



Original x =  [ 7 10  1  2  6  8  6  5  3  1]

Sorted x (out of place): [ 1  1  2  3  5  6  6  7  8 10]
x after sorting: [ 7 10  1  2  6  8  6  5  3  1]

x after in place sorting: [ 1  1  2  3  5  6  6  7  8 10]


In [93]:
X = np.random.randint(1,11,size=(5,5))


# We print X
print()
print('Original X = \n', X)
print()

# We sort the columns of X and print the sorted array
print()
print('X with sorted columns :\n', np.sort(X, axis = 0))

# We sort the rows of X and print the sorted array
print()
print('X with sorted rows :\n', np.sort(X, axis = 1))


Original X = 
 [[ 6  2  3  8  9]
 [ 4  2  1 10 10]
 [ 8  3  5 10 10]
 [ 4  4  9  5  4]
 [10  1  1  8  9]]


X with sorted columns :
 [[ 4  1  1  5  4]
 [ 4  2  1  8  9]
 [ 6  2  3  8  9]
 [ 8  3  5 10 10]
 [10  4  9 10 10]]

X with sorted rows :
 [[ 2  3  6  8  9]
 [ 1  2  4 10 10]
 [ 3  5  8 10 10]
 [ 4  4  4  5  9]
 [ 1  1  8  9 10]]


In [94]:
X = np.arange(60,0,-1).reshape(5,4,3)

print('X = \n',X, '\n')
print('sort X on axis=2 :\n', np.sort(X,axis=2), '\n')
print('sort X on axis=1 :\n', np.sort(X,axis=1), '\n')
print('sort X on axis=0 :\n', np.sort(X,axis=0), '\n')


X = 
 [[[60 59 58]
  [57 56 55]
  [54 53 52]
  [51 50 49]]

 [[48 47 46]
  [45 44 43]
  [42 41 40]
  [39 38 37]]

 [[36 35 34]
  [33 32 31]
  [30 29 28]
  [27 26 25]]

 [[24 23 22]
  [21 20 19]
  [18 17 16]
  [15 14 13]]

 [[12 11 10]
  [ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]] 

sort X on axis=2 :
 [[[58 59 60]
  [55 56 57]
  [52 53 54]
  [49 50 51]]

 [[46 47 48]
  [43 44 45]
  [40 41 42]
  [37 38 39]]

 [[34 35 36]
  [31 32 33]
  [28 29 30]
  [25 26 27]]

 [[22 23 24]
  [19 20 21]
  [16 17 18]
  [13 14 15]]

 [[10 11 12]
  [ 7  8  9]
  [ 4  5  6]
  [ 1  2  3]]] 

sort X on axis=1 :
 [[[51 50 49]
  [54 53 52]
  [57 56 55]
  [60 59 58]]

 [[39 38 37]
  [42 41 40]
  [45 44 43]
  [48 47 46]]

 [[27 26 25]
  [30 29 28]
  [33 32 31]
  [36 35 34]]

 [[15 14 13]
  [18 17 16]
  [21 20 19]
  [24 23 22]]

 [[ 3  2  1]
  [ 6  5  4]
  [ 9  8  7]
  [12 11 10]]] 

sort X on axis=0 :
 [[[12 11 10]
  [ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]

 [[24 23 22]
  [21 20 19]
  [18 17 16]
  [15 14 13]]

 [[36 35 3

**NOTE**
> Omitting the axis argument automatically selects the last and innermost dimension `axis=-1`, which is the rows in this example. Using `axis=None` flattens the array and performs a global sort.

# Set Operation

In [95]:
# We create a rank 1 ndarray
x = np.array([1,2,3,4,5])

# We create a rank 1 ndarray
y = np.array([6,7,2,8,4])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)

# We use set operations to compare x and y:
print()
print('All the elements of x and y:',np.union1d(x,y))

print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))

#To find the union of more than two arrays, use functools.reduce:
from functools import reduce
z=reduce(np.union1d, ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))
print("z = ",z)



x =  [1 2 3 4 5]

y =  [6 7 2 8 4]

All the elements of x and y: [1 2 3 4 5 6 7 8]
The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
z =  [1 2 3 4 6]


# Arithmetic operations and Broadcasting

## Element-wise arithmetic operations 

In [96]:
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])

# We print x
print()
print('x = ', x)

# We print y
print()
print('y = ', y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('x + y = ', x + y)
print('np.add(x,y) = ', np.add(x,y))
print()
print('x - y = ', x - y)
print('np.subtract(x,y) = ', np.subtract(x,y))
print()
print('x * y = ', x * y)
print('np.multiply(x,y) = ', np.multiply(x,y))
print()
print('x / y = ', x / y)
print('np.divide(x,y) = ', np.divide(x,y))


x =  [1 2 3 4]

y =  [5.5 6.5 7.5 8.5]

x + y =  [ 6.5  8.5 10.5 12.5]
np.add(x,y) =  [ 6.5  8.5 10.5 12.5]

x - y =  [-4.5 -4.5 -4.5 -4.5]
np.subtract(x,y) =  [-4.5 -4.5 -4.5 -4.5]

x * y =  [ 5.5 13.  22.5 34. ]
np.multiply(x,y) =  [ 5.5 13.  22.5 34. ]

x / y =  [0.1818 0.3077 0.4    0.4706]
np.divide(x,y) =  [0.1818 0.3077 0.4    0.4706]


In [97]:
# We create two  two-dimensional ndarrays
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)

# We print X
print()
print('X = \n', X)

# We print Y
print()
print('Y = \n', Y)
print()

# We perform basic element-wise operations using arithmetic symbols and functions
print('X + Y = \n', X + Y)
print()
print('add(X,Y) = \n', np.add(X,Y))
print()
print('X - Y = \n', X - Y)
print()
print('subtract(X,Y) = \n', np.subtract(X,Y))
print()
print('X * Y = \n', X * Y)
print()
print('multiply(X,Y) = \n', np.multiply(X,Y))
print()
print('X / Y = \n', X / Y)
print()
print('divide(X,Y) = \n', np.divide(X,Y))


X = 
 [[1 2]
 [3 4]]

Y = 
 [[5.5 6.5]
 [7.5 8.5]]

X + Y = 
 [[ 6.5  8.5]
 [10.5 12.5]]

add(X,Y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

X - Y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

subtract(X,Y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

X * Y = 
 [[ 5.5 13. ]
 [22.5 34. ]]

multiply(X,Y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]

X / Y = 
 [[0.1818 0.3077]
 [0.4    0.4706]]

divide(X,Y) = 
 [[0.1818 0.3077]
 [0.4    0.4706]]


## Broadcasting
Fundamentally, arrays can be broadcast against each other if their dimensions match or if one of the arrays has a size of 1.

In [98]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('3 * X = \n', 3 * X)
print()
print('3 + X = \n', 3 + X)
print()
print('X - 3 = \n', X - 3)
print()
print('X / 3 = \n', X / 3)


X = 
 [[1 2]
 [3 4]]

3 * X = 
 [[ 3  6]
 [ 9 12]]

3 + X = 
 [[4 5]
 [6 7]]

X - 3 = 
 [[-2 -1]
 [ 0  1]]

X / 3 = 
 [[0.3333 0.6667]
 [1.     1.3333]]


##### Creating ndarrays with Broadcasting

In [99]:
a=np.ones((4,4))
b=np.arange(1,5)
X = a * b
print(f"X =\n{X}")
Y = a * b.reshape(4,1)
print(f"Y =\n{Y}")

X =
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
Y =
[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


## Matrix multiplication
`numpy.matmul(a,b)` For 2-D arrays it is the matrix product.   
The @ operator can be used as a shorthand for `np.matmul` on ndarrays.

In [100]:
A=np.random.randint(1,10,(3,2))
print(f"X =\n{A}")
B=np.random.randint(1,10,(2,3))
print(f"B =\n{B}")

print("A×B=\n",A @ B)
print("B×A=\n",B @ A)

X =
[[1 6]
 [1 4]
 [6 2]]
B =
[[8 1 6]
 [2 4 8]]
A×B=
 [[20 25 54]
 [16 17 38]
 [52 14 52]]
B×A=
 [[45 64]
 [54 44]]


## Transpose of a matrix
[`numpy.transpose()`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html)

In [101]:
import numpy as np
x=np.arange(1,5).reshape(1,4)
print(f"X =\n{x}")
Y1= x.transpose() #out of place
print(f"Y1 =\n{Y1}")
print(f"X =\n{x}")
Y2 = np.transpose(x)#out of place
print(f"Y2 =\n{Y2}")
print(f"X =\n{x}")
#Y1 and Y2 are just views of original x array, they don't allocate more memory
print(f' Y1 and x share memory: {np.shares_memory(x, Y1)}')
print(f' Y1 and Y2 share memory: {np.shares_memory(Y1, Y2)}')

X =
[[1 2 3 4]]
Y1 =
[[1]
 [2]
 [3]
 [4]]
X =
[[1 2 3 4]]
Y2 =
[[1]
 [2]
 [3]
 [4]]
X =
[[1 2 3 4]]
 Y1 and x share memory: True
 Y1 and Y2 share memory: True


In [102]:
a = np.ones((255, 256, 3))
b= np.transpose(a, axes=(2,0,1))#change the order of axes
print(f'a shape: {a.shape}')
print(f'b shape: {b.shape}')

a shape: (255, 256, 3)
b shape: (3, 255, 256)


# numpy functions

## numpy Mathematical functions
 [full list of mathematica function](https://numpy.org/doc/stable/reference/routines.math.html)
- mean
- std
- sum, [nansum](https://numpy.org/doc/stable/reference/generated/numpy.nansum.html#numpy-nansum) , [cumsum](https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html#numpy.cumsum)
- prod, nanprod , cumprod
- max
- min
- exp &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$e^x$
- expm1 &emsp;&emsp;&emsp;&emsp;&emsp; $ e^x - 1$
- exp2 &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; $2^x$
- log &emsp;&emsp;&emsp;&emsp;&emsp;&emsp; $Ln(x)$
- log2 &emsp; &emsp;&emsp;&emsp;&emsp; ${Log}_{2}(s)$
- log10 &emsp;&emsp;&emsp;&emsp;&emsp; ${Log}_{10}(s)$
- log1p &emsp;&emsp;&emsp;&emsp;&emsp; $Ln(1+x)$
- sqrt   &emsp;&emsp;square-root 
- cbrt  &emsp;&emsp;cube-root 
- power
- square   &emsp;&emsp;&emsp;&emsp;&emsp;$x^2$
- clip(a, a_min, a_max)

> :memo: **Note** 
> Many NumPy’s functions behave in this way: If no axis is specified, then they perform an operation on the entire dataset (**flattened** ndarray ). Otherwise, they perform the operation in an **axis-wise** fashion.


In [103]:
X = np.array([
       [16, 3, 2, 13],
       [5, 10, 11, 8],
       [9, 6, 7, 12],
      # [4, 15, 14, 1]
  ])
print(f'X = \n{X}\n')
print(f'X.sum() = {X.sum()}') #instance method
print(f'np.sum(X) = {np.sum(X)}')#static method
print()
print(f'X.sum(axis=0) = {X.sum(axis=0)} ')
print(f'X.sum(axis=1) = {X.sum(axis=1)}\n')
print(f'np.sum(X,axis=0) = {np.sum(X,axis=0)}')
print(f'np.sum(X,axis=1) = {np.sum(X,axis=1)}')
print()
Y=[np.sum(X[i:i+2,j:j+2]) for i in [0] for j in [0, 2]]
print(f'{Y}')


X = 
[[16  3  2 13]
 [ 5 10 11  8]
 [ 9  6  7 12]]

X.sum() = 102
np.sum(X) = 102

X.sum(axis=0) = [30 19 20 33] 
X.sum(axis=1) = [34 34 34]

np.sum(X,axis=0) = [30 19 20 33]
np.sum(X,axis=1) = [34 34 34]

[34, 34]


In [104]:
# We create a 2 x 2 ndarray
X = np.array([[1,2], [3,4]])

# We print x
print()
print('X = \n', X)
print()

print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Sum of all elements in the columns of X:', X.sum(axis=0))
print('Sum of all elements in the rows of X:', X.sum(axis=1))
print()
print('Standard Deviation of all elements in X:', X.std())
print('Standard Deviation of all elements in the columns of X:', X.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', X.std(axis=1))
print()
print('Median of all elements in X:', np.median(X))
print('Median of all elements in the columns of X:', np.median(X,axis=0))
print('Median of all elements in the rows of X:', np.median(X,axis=1))
print()
print('Maximum value of all elements in X:', X.max())
print('Maximum value of all elements in the columns of X:', X.max(axis=0))
print('Maximum value of all elements in the rows of X:', X.max(axis=1))
print()
print('Minimum value of all elements in X:', X.min())
print('Minimum value of all elements in the columns of X:', X.min(axis=0))
print('Minimum value of all elements in the rows of X:', X.min(axis=1))

#
print('x = \n', X)

# We apply different mathematical functions to all elements of x
print()
print('EXP(x) =\n', np.exp(X))
print()
print('SQRT(x) =\n',np.sqrt(X))
print()
print('POW(x,2) =\n',np.power(X,2)) # We raise all elements to the power of 2


X = 
 [[1 2]
 [3 4]]

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Sum of all elements in the columns of X: [4 6]
Sum of all elements in the rows of X: [3 7]

Standard Deviation of all elements in X: 1.118033988749895
Standard Deviation of all elements in the columns of X: [1. 1.]
Standard Deviation of all elements in the rows of X: [0.5 0.5]

Median of all elements in X: 2.5
Median of all elements in the columns of X: [2. 3.]
Median of all elements in the rows of X: [1.5 3.5]

Maximum value of all elements in X: 4
Maximum value of all elements in the columns of X: [3 4]
Maximum value of all elements in the rows of X: [2 4]

Minimum value of all elements in X: 1
Minimum value of all elements in the columns of X: [1 2]
Minimum value of all elements in the rows of X: [1 3]
x = 
 [[1 2]
 [3 4]]

EXP(x) =
 [[ 2.7183  7.3891]
 [20.0855 54.5982]]

SQRT(x) =
 [[1.     1

In [105]:
print(1/(1+np.exp(-X)))

[[0.7311 0.8808]
 [0.9526 0.982 ]]


## Vectorize python function


In [106]:
def cub(num):
    return num**3

cub_numpy=np.vectorize(cub)
x=np.arange(5)
y=cub_numpy(x)
print('x = ', x)
print('y = ', y)

x =  [0 1 2 3 4]
y =  [ 0  1  8 27 64]


## swap axes

In [107]:
X = np.arange(24).reshape(2,3,4)
print(f'Original X is:\n {X}\n')
Y=np.swapaxes(X,1,2)

print(f'X shape: {X.shape}')
print(f'Y shape: {Y.shape}')

print(f'Y is:\n {Y}')

Original X is:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

X shape: (2, 3, 4)
Y shape: (2, 4, 3)
Y is:
 [[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


## numpy.linalg.norm
[Reed more ](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
> norm for vectors:
- p norm includes: 1, 2, -1, -2
- None: Default is 2-norm
-  inf : $max(abs(x_i))$
-  -inf : $min(abs(x_i)$ 

> norm for **matrices**
- ‘fro’ : Frobenius norm
- ‘nuc’ :nuclear norm $\sum \sigma_i$

In [108]:
a = np.arange(5) 
print(a)
print('1-norm: ', np.linalg.norm(a, ord=1))
print('2-norm: ', np.linalg.norm(a, ord=2))
print('3-norm: ', np.linalg.norm(a, ord=3))
print('100-norm: ', np.linalg.norm(a, ord=100))
print('inf-norm: ', np.linalg.norm(a, ord=np.inf))
print('-inf-norm: ', np.linalg.norm(a, ord=-np.inf))

[0 1 2 3 4]
1-norm:  10.0
2-norm:  5.477225575051661
3-norm:  4.641588833612778
100-norm:  4.000000000000013
inf-norm:  4.0
-inf-norm:  0.0


# Practical Example 1: Implementing a Maclaurin Series

In [109]:
import math
   
factorial=np.vectorize(math.factorial)

def my_exp(value, terms=10):
    numbers=np.arange(terms,dtype=np.float32)
    xs=np.full(numbers.shape, value, dtype=np.float32)
    return  sum((xs**numbers)/factorial(numbers.astype(np.int32)))
    
  
x = 3
print(f"{'n':<7} {'e^' + str(x):<10} {'error':<10}")
for n in range(1, 14):
    maclaurin = my_exp(x, terms=n)
    print(f"{n:<7} {maclaurin:<10.03f} {math.exp(x) - maclaurin:<10.03f}")

n       e^3        error     
1       1.000      19.086    
2       4.000      16.086    
3       8.500      11.586    
4       13.000     7.086     
5       16.375     3.711     
6       18.400     1.686     
7       19.412     0.673     
8       19.846     0.239     
9       20.009     0.076     
10      20.063     0.022     
11      20.080     0.006     
12      20.084     0.001     
13      20.085     0.000     


https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html

In [110]:
x = np.arange(1,10).reshape(3,3)
y= x.reshape(-1 )#flatten a array
print(y.shape)

(9,)
